DROP DATABASE IF EXISTS phoneservice;
DROP USER IF EXISTS `phone_service`@`%`;
CREATE DATABASE IF NOT EXISTS phoneservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `phone_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `phoneservice`.* TO `phone_service`@`%`;
FLUSH PRIVILEGES;